meta:
  id: telebot-constructor
  updated_at: 2025-06-01T08:35:10Z
  owner: vladimir-podlevskikh

pipeline:
  - code: "0"
    name: idea_to_tech_draft
    substeps:
      "0.1": {desc: one_liner_problem,     status: done,         assignee: vladimir}
      "0.2": {desc: msc_backlog,           status: done,         assignee: vladimir}
      "0.3": {desc: stack_selection,       status: done,         assignee: vladimir}
      "0.4": {desc: ux_er_diagrams,        status: in_progress,  assignee: vladimir}
      "0.5": {desc: repo_bootstrap,        status: done,         assignee: vladimir}
  - code: "1"
    name: solution_definition
    substeps:
      "1.1": {desc: lean_spec,             status: not_started}
      "1.2": {desc: c4_diagrams,           status: not_started}
      "1.3": {desc: openapi_contracts,     status: not_started}
      "1.4": {desc: data_schema_design,    status: not_started}
      "1.5": {desc: cost_sheet,            status: not_started}
  - code: "2"
    name: rapid_prototype
    substeps:
      "2.1": {desc: clickable_ui_prototype, status: not_started}
      "2.2": {desc: backend_skeleton,       status: not_started}
      "2.3": {desc: docker_compose_stack,   status: not_started}
      "2.4": {desc: smoke_script,           status: not_started}
      "2.5": {desc: perf_baseline,          status: not_started}
  - code: "3"
    name: mvp_build
    substeps:
      "3.1": {desc: critical_user_flows,    status: not_started}
      "3.2": {desc: backend_implementation, status: not_started}
      "3.3": {desc: spa_implementation,     status: not_started}
      "3.4": {desc: ci_setup,               status: not_started}
      "3.5": {desc: docker_helm_chart,      status: not_started}
  - code: "4"
    name: automated_qa_observability
    substeps:
      "4.1": {desc: contract_tests,         status: not_started}
      "4.2": {desc: e2e_tests,              status: not_started}
      "4.3": {desc: synthetic_monitoring,   status: not_started}
      "4.4": {desc: distributed_tracing,    status: not_started}
      "4.5": {desc: alerting_rules,         status: not_started}
  - code: "5"
    name: production_launch_pipeline
    substeps:
      "5.1": {desc: iac_infra,              status: not_started}
      "5.2": {desc: blue_green_deploy,      status: not_started}
      "5.3": {desc: backups_drt,            status: not_started}
      "5.4": {desc: cdn_https,              status: not_started}
      "5.5": {desc: runbook_incident,       status: not_started}
  - code: "6"
    name: optimization_refactor
    substeps:
      "6.1": {desc: profiling_optimization, status: not_started}
      "6.2": {desc: quality_gates,          status: not_started}
      "6.3": {desc: tech_debt_grooming,     status: not_started}
      "6.4": {desc: feature_toggle_service, status: not_started}
      "6.5": {desc: cve_scan_auto_patch,    status: not_started}
  - code: "7"
    name: architecture_hardening
    substeps:
      "7.1": {desc: platform_services,      status: not_started}
      "7.2": {desc: api_gateway,            status: not_started}
      "7.3": {desc: central_config,         status: not_started}
      "7.4": {desc: slo_chaos_tests,        status: not_started}
      "7.5": {desc: secrets_manager,        status: not_started}
  - code: "8"
    name: data_ml_pipeline
    substeps:
      "8.1": {desc: domain_events_stream,   status: not_started}
      "8.2": {desc: elt_warehouse,          status: not_started}
      "8.3": {desc: offline_training,       status: not_started}
      "8.4": {desc: online_inference,       status: not_started}
      "8.5": {desc: governance_policies,    status: not_started}
  - code: "9"
    name: global_scale
    substeps:
      "9.1": {desc: multi_region_k8s,       status: not_started}
      "9.2": {desc: geo_replication,        status: not_started}
      "9.3": {desc: edge_cdn_ssr,           status: not_started}
      "9.4": {desc: tenant_isolation,       status: not_started}
      "9.5": {desc: dr_drill,               status: not_started}
  - code: "10"
    name: platform_ecosystem
    substeps:
      "10.1": {desc: versioned_openapi,     status: not_started}
      "10.2": {desc: oauth2_server,         status: not_started}
      "10.3": {desc: webhook_hub,           status: not_started}
      "10.4": {desc: plugin_framework,      status: not_started}
      "10.5": {desc: dev_portal,            status: not_started}
  - code: "11"
    name: continuous_delivery_maintenance
    substeps:
      "11.1": {desc: trunk_based_dev,       status: not_started}
      "11.2": {desc: semantic_release,      status: not_started}
      "11.3": {desc: progressive_delivery,  status: not_started}
      "11.4": {desc: finops_dashboard,      status: not_started}
      "11.5": {desc: auto_update_libs,      status: not_started}
  - code: "12"
    name: lifecycle_management
    substeps:
      "12.1": {desc: support_matrix,        status: not_started}
      "12.2": {desc: deprecation_roadmap,   status: not_started}
      "12.3": {desc: security_pen_tests,    status: not_started}
      "12.4": {desc: compliance_automation, status: not_started}
      "12.5": {desc: iac_clean_down,        status: not_started}

